version: '3'

services:
  front:
    env_file:
     - .env.dev
    container_name: upline-frontend-dev
    command: sh -c "npm run dev"
    ports:
      - '5173:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true

