version: '3'

services:
  front:
    build: .
    image: front
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - .:/usr/upline/front
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

